"""Bundle the real game modules + a scenario into ONE luau chunk (see README.md).

The luau CLI has no `io`, and shadowing the builtin `require` is risky, so every
module body is inlined inside `(function() ... end)()` and resolved through a
LOCAL `require` shim declared before them (lexical scoping — guaranteed).
"""
import io, os, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")) + "/"
HERE = os.path.dirname(os.path.abspath(__file__))

# proxy path -> source file, in dependency order
MODULES = [
    ("Shared.GridUtil", "src/shared/GridUtil.lua"),
    ("Shared.config.CakeConfig", "src/shared/config/CakeConfig.lua"),
    ("Shared.config.TreasureConfig", "src/shared/config/TreasureConfig.lua"),
    ("Shared.CakeOps", "src/shared/CakeOps.lua"),
    ("__TreasureService", "src/server/game/services/TreasureService.lua"),
]



SCENARIO_FILE = os.environ.get("SCENARIO_FILE", "treasure_scenario.lua")


def read(path):
    with io.open(ROOT + path, encoding="utf-8", newline="") as f:
        return f.read()


def read_local(name):
    with io.open(os.path.join(HERE, name), encoding="utf-8", newline="") as f:
        return f.read()


out = []
out.append("--!nolint\n-- GENERATED by build_sim.py — do not edit\n")
out.append("local stub = (function()\n" + read_local("roblox_stub.lua") + "\nend)()\n")
out.append(read_local("harness_head.lua"))

out.append("\n-- ── inlined game modules ───────────────────────────────────\n")
for proxy_path, src_path in MODULES:
    body = read(src_path)
    out.append(f"\n-- ===== {src_path} =====\n")
    out.append(f'__REGISTRY["{proxy_path}"] = (function()\n{body}\nend)()\n')

body = read_local(SCENARIO_FILE)
body = body.replace("__SEED__", sys.argv[1] if len(sys.argv) > 1 else "20260726")
body = body.replace("__SCENARIO__", sys.argv[2] if len(sys.argv) > 2 else "easy")
out.append(body)

dest = os.path.join(HERE, "sim.luau")
with io.open(dest, "w", encoding="utf-8", newline="\n") as f:
    f.write("".join(out))
print("wrote", dest)
