"""Bundle the real game modules + a scenario into ONE luau chunk (see README.md).

The luau CLI has no `io`, and shadowing the builtin `require` is risky, so every
module body is inlined inside `(function() ... end)()` and resolved through a
LOCAL `require` shim declared before them (lexical scoping — guaranteed).
"""
import io, os, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")) + "/"
HERE = os.path.dirname(os.path.abspath(__file__))

SCENARIO_FILE = os.environ.get("SCENARIO_FILE", "treasure_scenario.lua")

# Per-scenario module list, in dependency order.
#   (proxy path, source file[, script proxy path])
# The optional third element sets the global `script` for that module's body,
# which is how a module that reaches SIBLINGS (`script.Parent:WaitForChild(...)`)
# resolves them — the Analytics helpers all do.
MODULE_SETS = {
    "treasure_scenario.lua": [
        ("Shared.GridUtil", "src/shared/GridUtil.lua"),
        ("Shared.config.CakeConfig", "src/shared/config/CakeConfig.lua"),
        ("Shared.config.TreasureConfig", "src/shared/config/TreasureConfig.lua"),
        ("Shared.CakeOps", "src/shared/CakeOps.lua"),
        ("__TreasureService", "src/server/game/services/TreasureService.lua"),
    ],
    "analytics_scenario.lua": [
        ("Shared.config.AnalyticsConfig", "src/shared/config/AnalyticsConfig.lua"),
        ("Shared.config.PlaceConfig", "src/shared/config/PlaceConfig.lua"),
        (
            "Server.subscriptions.Analytics.Sink",
            "src/server/common/subscriptions/Analytics/Sink.lua",
            "Server.subscriptions.Analytics.Sink",
        ),
        (
            "Server.subscriptions.Analytics.Session",
            "src/server/common/subscriptions/Analytics/Session.lua",
            "Server.subscriptions.Analytics.Session",
        ),
        (
            "Server.subscriptions.Analytics.Ingest",
            "src/server/common/subscriptions/Analytics/Ingest.lua",
            "Server.subscriptions.Analytics.Ingest",
        ),
    ],
}
# pacing_scenario has always run on the cake module set (it measures clear time
# and income against the same configs), so it is named rather than left to the
# fallback — a scenario silently getting the wrong module list looks like a pass.
# ⚠ It also needs UpgradeConfig since 2026-08-05: its fresh/maxed eater used to
# HARDCODE radius/depth/rate/capacity/burnSpeed, and a later hand-tune of those
# values left the scenario measuring an eater the game no longer ships (it was
# still reporting a 3.4-stud base bite two commits after the game moved to 2.4).
MODULE_SETS["pacing_scenario.lua"] = MODULE_SETS["treasure_scenario.lua"] + [
    ("Shared.config.UpgradeConfig", "src/shared/config/UpgradeConfig.lua"),
    # TutorialConfig is here for ONE field — `burnPromptStat`, the stat whose
    # tier-1 price section D asserts is reachable. Hardcoding "biteRadius" there
    # would make the assertion silently pass the day the gate is retargeted, which
    # is the exact failure mode the section exists to prevent.
    ("Shared.config.TutorialConfig", "src/shared/config/TutorialConfig.lua"),
]

# layereater_scenario drives the REAL CakeFieldService (not a re-implementation
# of the bite math like pacing does), so it needs the server data modules the
# service takes in Init — and CakeConfigData pulls in every shared config.
MODULE_SETS["layereater_scenario.lua"] = [
    ("Shared.GridUtil", "src/shared/GridUtil.lua"),
    ("Shared.config.CakeConfig", "src/shared/config/CakeConfig.lua"),
    ("Shared.config.UpgradeConfig", "src/shared/config/UpgradeConfig.lua"),
    ("Shared.config.BodyConfig", "src/shared/config/BodyConfig.lua"),
    ("Shared.config.PetConfig", "src/shared/config/PetConfig.lua"),
    ("Shared.config.TreasureConfig", "src/shared/config/TreasureConfig.lua"),
    ("Shared.CakeOps", "src/shared/CakeOps.lua"),
    ("__CakeConfigData", "src/server/common/data/CakeConfigData.lua"),
    ("__CakeStateData", "src/server/game/data/CakeStateData.lua"),
    ("__CakeFieldService", "src/server/game/services/CakeFieldService.lua"),
]
MODULES = MODULE_SETS.get(SCENARIO_FILE, MODULE_SETS["treasure_scenario.lua"])


def read(path):
    with io.open(ROOT + path, encoding="utf-8", newline="") as f:
        return f.read()


def read_local(name):
    with io.open(os.path.join(HERE, name), encoding="utf-8", newline="") as f:
        return f.read()


out = []
out.append("--!nolint\n-- GENERATED by build_sim.py — do not edit\n")
out.append("local stub = (function()\n" + read_local("roblox_stub.lua") + "\nend)()\n")
out.append(read_local("harness_head.lua"))

out.append("\n-- ── inlined game modules ───────────────────────────────────\n")
for entry in MODULES:
    proxy_path, src_path = entry[0], entry[1]
    script_path = entry[2] if len(entry) > 2 else None
    body = read(src_path)
    out.append(f"\n-- ===== {src_path} =====\n")
    if script_path:
        # Modules capture `script` at load time, so it is re-pointed per body.
        out.append(f'script = makeProxy("{script_path}")\n')
    out.append(f'__REGISTRY["{proxy_path}"] = (function()\n{body}\nend)()\n')

body = read_local(SCENARIO_FILE)
body = body.replace("__SEED__", sys.argv[1] if len(sys.argv) > 1 else "20260726")
body = body.replace("__SCENARIO__", sys.argv[2] if len(sys.argv) > 2 else "easy")
out.append(body)

dest = os.path.join(HERE, "sim.luau")
with io.open(dest, "w", encoding="utf-8", newline="\n") as f:
    f.write("".join(out))
print("wrote", dest)
